"""Installation helper — copies the plugin to the app-data directory and
writes a stub entry-point into DaVinci Resolve's Scripts/Utility folder.

Run:  python install.py

Layout produced:

    <app_dir>/
        main.py
        gui.py
        src/
        assets/
        requirements.txt
        ...

    <scripts_dir>/
        Clutter.py      <-- single file, Resolve shows just "Clutter" menu item

AutoSubs pattern: stub in Scripts/Utility points to app dir at runtime.
"""

from __future__ import annotations
import os
import shutil
import sys
from pathlib import Path

_PLUGIN_DIR = Path(__file__).resolve().parent
_PLUGIN_NAME = "Clutter"

# Where the actual app files live (outside DaVinci Resolve folders).
_APP_DIRS = {
    "win32":  Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local")) / _PLUGIN_NAME,
    "darwin": Path.home() / "Library" / "Application Support" / _PLUGIN_NAME,
    "linux":  Path.home() / ".local" / "share" / _PLUGIN_NAME,
}

# DaVinci Resolve Scripts/Utility folder (stub goes here).
_SCRIPTS_DIRS = {
    "win32":  Path(os.environ.get("APPDATA", "~")) / "Blackmagic Design" / "DaVinci Resolve"
              / "Support" / "Fusion" / "Scripts" / "Utility",
    "darwin": Path.home() / "Library" / "Application Support" / "Blackmagic Design"
              / "DaVinci Resolve" / "Fusion" / "Scripts" / "Utility",
    "linux":  Path.home() / ".local" / "share" / "DaVinciResolve" / "Fusion" / "Scripts" / "Utility",
}

_STUB_TEMPLATE = '''\
"""Clutter - DaVinci Resolve plugin stub. Auto-generated by install.py."""
import sys
from pathlib import Path

_APP_DIR = Path("{app_dir}")
if str(_APP_DIR) not in sys.path:
    sys.path.insert(0, str(_APP_DIR))

import main as _clutter_main

# DaVinci Resolve injects `resolve` into this file's globals at script launch.
# Forward it into main.py's module namespace so _acquire_resolve() finds it.
_resolve_obj = globals().get("resolve")
if _resolve_obj is not None:
    _clutter_main.resolve = _resolve_obj

_clutter_main.main()
'''


def main() -> None:
    platform = sys.platform
    if platform not in _APP_DIRS:
        print(f"Unsupported platform: {platform}")
        sys.exit(1)

    app_dir     = _APP_DIRS[platform].expanduser()
    scripts_dir = _SCRIPTS_DIRS[platform].expanduser()
    stub_path   = scripts_dir / f"{_PLUGIN_NAME}.py"
    old_dest    = scripts_dir / _PLUGIN_NAME  # old subfolder layout

    print(f"App directory:  {app_dir}")
    print(f"Stub location:  {stub_path}")
    if old_dest.exists() and old_dest.is_dir():
        print(f"Old install:    {old_dest}  (will be removed)")
    print()

    answer = input("Install/update plugin? [y/N] ").strip().lower()
    if answer != "y":
        print("Aborted.")
        return

    # 1. Copy app files to the platform data directory.
    app_dir.mkdir(parents=True, exist_ok=True)
    action = "Updating" if any(app_dir.iterdir()) else "Installing"
    print(f"{action} app files: {app_dir}")
    shutil.copytree(
        str(_PLUGIN_DIR),
        str(app_dir),
        ignore=shutil.ignore_patterns(
            ".git", ".claude", "__pycache__", "*.pyc",
            "install.py", "INSTALL.md", "README.md",
        ),
        dirs_exist_ok=True,
    )

    # 2. Write stub into Scripts/Utility/.
    scripts_dir.mkdir(parents=True, exist_ok=True)
    stub_path.write_text(_STUB_TEMPLATE.format(app_dir=app_dir.as_posix()),
                         encoding="utf-8")
    print(f"Stub written:   {stub_path}")

    # 3. Remove old Clutter/ subfolder if it still exists from a prior install.
    if old_dest.exists() and old_dest.is_dir():
        print(f"Removing old installation: {old_dest}")
        shutil.rmtree(old_dest)

    print()
    print("Next steps:")
    print("  1. Install Python 3.12 dependencies (Python 3.13+ will segfault):")
    print(f'     py -3.12 -m pip install -r "{app_dir / "requirements.txt"}"')
    print("  2. Install ffmpeg and add to PATH:")
    print("     https://ffmpeg.org/download.html")
    print("  3. Open DaVinci Resolve")
    print("  4. Go to: Workspace > Scripts > Utility > Clutter")
    print()
    print("Done!")


if __name__ == "__main__":
    main()
